CREATE TABLE IF NOT EXISTS returns (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  shop_id TEXT NOT NULL REFERENCES shops(id) ON DELETE RESTRICT,
  sales_rep_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'voided')),
  notes TEXT,
  idempotency_key TEXT NOT NULL,
  total_credit NUMERIC NOT NULL CHECK (total_credit >= 0),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (sales_rep_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_returns_order_id ON returns(order_id);
CREATE INDEX IF NOT EXISTS idx_returns_shop_id ON returns(shop_id);

CREATE TABLE IF NOT EXISTS return_items (
  id TEXT PRIMARY KEY,
  return_id TEXT NOT NULL REFERENCES returns(id) ON DELETE RESTRICT,
  order_item_id TEXT NOT NULL REFERENCES order_items(id) ON DELETE RESTRICT,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_credit NUMERIC NOT NULL CHECK (unit_credit >= 0),
  line_credit NUMERIC NOT NULL CHECK (line_credit >= 0)
);

CREATE INDEX IF NOT EXISTS idx_return_items_return_id ON return_items(return_id);
CREATE INDEX IF NOT EXISTS idx_return_items_order_item_id ON return_items(order_item_id);

CREATE TABLE IF NOT EXISTS credit_notes (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  return_id TEXT NOT NULL UNIQUE REFERENCES returns(id) ON DELETE RESTRICT,
  amount NUMERIC NOT NULL CHECK (amount >= 0),
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('approved', 'voided')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_credit_notes_order_id ON credit_notes(order_id);

CREATE TABLE IF NOT EXISTS customer_credit_resolutions (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  shop_id TEXT NOT NULL REFERENCES shops(id) ON DELETE RESTRICT,
  admin_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  resolution_type TEXT NOT NULL CHECK (resolution_type IN ('refund', 'account_credit')),
  amount NUMERIC NOT NULL CHECK (amount > 0),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customer_credit_resolutions_order_id
  ON customer_credit_resolutions(order_id);

COMMENT ON TABLE returns IS 'Append-only product return documents. Original orders and order_items remain immutable.';
COMMENT ON TABLE credit_notes IS 'Financial credits generated by confirmed returns.';
COMMENT ON TABLE customer_credit_resolutions IS 'Append-only record of refund or account-credit handling for invoice overpayments.';
